name: e2eTests
on:
    push:
        branches:
            - add-cypress-tests
jobs:
    e2etests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - run: yarn install --frozen-lockfile --prefer-offline
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                build: npm run e2e:build-ci
                start: npm run e2e:run-server